CREATE TABLE CATEGORIA_CLIENTE
(
  ID_CATEGORIA   SERIAL UNIQUE PRIMARY KEY,
  NOME_CATEGORIA VARCHAR(100) NOT NULL,
  DESCONTO       FLOAT        NOT NULL
);

CREATE TABLE CLIENTE
(
  ID_CLIENTE           SERIAL UNIQUE PRIMARY KEY,
  NOME_CLIENTE         VARCHAR(200) NOT NULL,
  TELEFONE             VARCHAR(30)  NOT NULL,
  ID_CATEGORIA_CLIENTE INT REFERENCES CATEGORIA_CLIENTE (ID_CATEGORIA)

);

CREATE TABLE FUNCIONARIO
(
  ID_FUNCIONARIO   SERIAL UNIQUE PRIMARY KEY,
  NOME_FUNCIONARIO VARCHAR(200) NOT NULL,
  ENDERECO         VARCHAR(200) NOT NULL,
  TELEFONE         VARCHAR(30)  NOT NULL
);

CREATE TABLE DIARISTA
(
  ID_DIARISTA   SERIAL UNIQUE PRIMARY KEY,
  NOME_DIARISTA VARCHAR(200) NOT NULL,
  ENDERECO      VARCHAR(200) NOT NULL,
  TELEFONE      VARCHAR(30)  NOT NULL
);

CREATE TABLE SERVICOS
(
  ID_SERVICO    SERIAL UNIQUE PRIMARY KEY,
  NOME_SERVICO  VARCHAR(100) NOT NULL,
  VALOR_SERVICO FLOAT        NOT NULL

);

CREATE TABLE SOLICITACAO
(
  ID_SOLICITACAO    SERIAL UNIQUE PRIMARY KEY,
  ID_CLIENTE        INT REFERENCES CLIENTE (ID_CLIENTE),
  ID_FUNCIONARIO    INT REFERENCES FUNCIONARIO (ID_FUNCIONARIO),
  DATA              DATE  NOT NULL,
  HORA              TIME  NOT NULL,
  VALOR_SOLICITACAO FLOAT NOT NULL
);

CREATE TABLE DIARISTA_SERVICO
(
  ID_DIARISTA INT REFERENCES DIARISTA (ID_DIARISTA),
  ID_SERVICO  INT REFERENCES SERVICOS (ID_SERVICO)
);

CREATE TABLE SOLICITACAO_SERVICO
(
  ID_SOLICITACAO       INT REFERENCES SOLICITACAO (ID_SOLICITACAO),
  ID_CLIENTE           INT REFERENCES CLIENTE (ID_CLIENTE),
  ID_CATEGORIA_CLIENTE INT REFERENCES CATEGORIA_CLIENTE (ID_CATEGORIA),
  ID_FUNCIONARIO       INT REFERENCES FUNCIONARIO (ID_FUNCIONARIO),
  ID_SERVICO           INT REFERENCES SERVICOS (ID_SERVICO),
  ID_DIARISTA          INT REFERENCES DIARISTA (ID_DIARISTA)
);
---------------------------------------------------Povoamento-----------------------------------------------------------

INSERT INTO CATEGORIA_CLIENTE(NOME_CATEGORIA, DESCONTO)
VALUES ('BRONZE', 0.1);
INSERT INTO CATEGORIA_CLIENTE(NOME_CATEGORIA, DESCONTO)
VALUES ('PRATA', 0.3);
INSERT INTO CATEGORIA_CLIENTE(NOME_CATEGORIA, DESCONTO)
VALUES ('OURO', 0.5);

INSERT INTO CLIENTE(NOME_CLIENTE, TELEFONE, ID_CATEGORIA_CLIENTE)
VALUES ('JOÃO', '998500295', 1);
INSERT INTO CLIENTE(NOME_CLIENTE, TELEFONE, ID_CATEGORIA_CLIENTE)
VALUES ('PEDRO', '998657901', 2);
INSERT INTO CLIENTE(NOME_CLIENTE, TELEFONE, ID_CATEGORIA_CLIENTE)
VALUES ('RICARDO', '5132715375', 3);
INSERT INTO CLIENTE(NOME_CLIENTE, TELEFONE, ID_CATEGORIA_CLIENTE)
VALUES ('CONCEIÇÃO', '1231242615', 2);
INSERT INTO CLIENTE(NOME_CLIENTE, TELEFONE, ID_CATEGORIA_CLIENTE)
VALUES ('EDSON', '1312213333', 3);
INSERT INTO CLIENTE(NOME_CLIENTE, TELEFONE, ID_CATEGORIA_CLIENTE)
VALUES ('PAULO', '145345552', 1);

INSERT INTO FUNCIONARIO(NOME_FUNCIONARIO, ENDERECO, TELEFONE)
VALUES ('', 'AVENIDA MIGUEL ROSA', '8798787361');
INSERT INTO FUNCIONARIO(NOME_FUNCIONARIO, ENDEREÇO, TELEFONE)
VALUES ('PABLO', 'AVENIDA FREI SERAFIM', '87876311312');
INSERT INTO FUNCIONARIO(NOME_FUNCIONARIO, ENDEREÇO, TELEFONE)
VALUES ('CHICO', 'RUA TERESINHA', '9876546889');
INSERT INTO FUNCIONARIO(NOME_FUNCIONARIO, ENDEREÇO, TELEFONE)
VALUES ('WANESSA', 'AVENIDA PIREZ DE CASTRO', '9897909876');
INSERT INTO FUNCIONARIO(NOME_FUNCIONARIO, ENDEREÇO, TELEFONE)
VALUES ('DEBORA', 'RUA 100', '8798731132');
INSERT INTO FUNCIONARIO(NOME_FUNCIONARIO, ENDEREÇO, TELEFONE)
VALUES ('JUVENAL', 'RUA 90', '9876588990');

INSERT INTO DIARISTA(NOME_DIARISTA, ENDERECO, TELEFONE)
VALUES ('MARIA', 'BAIRRO FLORES', '123123877');
INSERT INTO DIARISTA(NOME_DIARISTA, ENDERECO, TELEFONE)
VALUES ('JOANA', 'BAIRRO ININGA', '323131311');
INSERT INTO DIARISTA(NOME_DIARISTA, ENDERECO, TELEFONE)
VALUES ('HELCIO', 'BAIRRO PORTO ALEGRE', '0869909888');
INSERT INTO DIARISTA(NOME_DIARISTA, ENDERECO, TELEFONE)
VALUES ('JESSICA', 'BAIRRO HORTO', '445323113');
INSERT INTO DIARISTA(NOME_DIARISTA, ENDERECO, TELEFONE)
VALUES ('BRUNO', 'BAIRRO DIRCEU', '123123877');



-------------------------------------------------- Funções -------------------------------------------------------------
  ---> Inserir
CREATE OR REPLACE FUNCTION INSERIR(TABELA TEXT, VALOR TEXT)
  RETURNS VOID AS
$$
DECLARE
  COMANDO TEXT;

BEGIN

  COMANDO := 'INSERT INTO ' || $1 || ' VALUES(DEFAULT,' || $2 || ');';

  EXECUTE COMANDO;
END;

$$ LANGUAGE plpgsql;

select inserir('funcionario', ''''' ,''rua 18'',''9886788776''');

--->Update
drop function atualizar(tabela text, campo text, valorantigo text);
create or replace function atualizar(tabela text, campo text,valornovo text,condicao text,valor_condicao text)
  returns void as
$$
declare
  comando TEXT;

begin

  comando := 'UPDATE ' || tabela || ' SET '  || $2 || ' = ' ||$3 ||' where ' || $4 || ' = ' || valor_condicao;
  execute comando;

end;
$$ language plpgsql;

select atualizar('funcionario','nome_funcionario','''junior''','id_funcionario','5');


--->Delete

create or replace function deletar(tabela text,campo text,valor text)
returns void as $$
  declare
    comando text;
    begin
    comando:= 'delete from ' ||$1|| ' where ' ||$2|| '= '''||$3||'''';

    execute comando;
  end;
  $$ language plpgsql;



---------------------------------------------Trigger--------------------------------------------------------------------
----- feedback
CREATE TRIGGER TGR_FEEDBACK_OPERACAO
  AFTER INSERT OR
  UPDATE OR DELETE
  ON funcionario
  FOR EACH ROW EXECUTE PROCEDURE FEEDBACK_OPERACAO();

DROP FUNCTION FEEDBACK_OPERACAO() CASCADE;

CREATE OR REPLACE FUNCTION FEEDBACK_OPERACAO()
  RETURNS TRIGGER AS
$$

DECLARE
BEGIN
  IF (TG_OP = 'INSERT')
  THEN
    RAISE NOTICE 'INSERCAO FEITA COM SUCESSO!';
  END IF;
  IF (TG_OP = 'UPDATE')
  THEN
    RAISE NOTICE 'ALTERACAO FEITA COM SUCESSO!';
  END IF;
  IF (TG_OP = 'DELETE')
  THEN
    RAISE NOTICE 'DELETADO COM SUCESSO!';
  END IF;
  RETURN NULL ;
END;
$$
LANGUAGE plpgsql;


----------

create or replace function notvaluesnull()
returns trigger as $$
  begin
    if new.nome_funcionario  is null  or new.NOME_FUNCIONARIO = '' then
    raise exception 'nome nulo';
    end if;
    return null;
  end;

  $$language plpgsql;

create  trigger notnullfunc before insert or update on funcionario  FOR EACH ROW EXECUTE PROCEDURE notvaluesnull();
drop trigger notnullfunc on funcionario cascade ;
----------------------------------------------teste função inserir------------------------------------------------------
select inserir('funcionario', ''''' ,''rua 18'',''98867887731231''');
select inserir('categoria_cliente', '''platina3'',''90''');
select inserir('cliente', '''henrique'',''9098877889'',''1''');
select inserir('diarista', '''paula'',''bairro dirceu'',''1234567777''');
select inserir('servicos', '''lavar roupa'',''25''');

insert into FUNCIONARIO values (default,'','rua20','65767565765');

select deletar('funcionario','nome_funcionario','');


select * from funcionario
