CREATE TABLE CATEGORIA_CLIENTE(
  ID_CATEGORIA SERIAL UNIQUE PRIMARY KEY,
  NOME_CATEGORIA VARCHAR(100) NOT NULL ,
  DESCONTO FLOAT NOT NULL
);

CREATE TABLE CLIENTE (
  ID_CLIENTE SERIAL UNIQUE PRIMARY KEY,
  NOME_CLIENTE VARCHAR(200) NOT NULL ,
  TELEFONE VARCHAR(30) NOT NULL ,
  ID_CATEGORIA_CLIENTE INT REFERENCES CATEGORIA_CLIENTE(ID_CATEGORIA)

);

CREATE TABLE FUNCIONARIO(
  ID_FUNCIONARIO SERIAL UNIQUE PRIMARY KEY,
  NOME_FUNCIONARIO VARCHAR(200) NOT NULL,
  ENDEREÇO VARCHAR(200) NOT NULL ,
  TELEFONE VARCHAR(30) NOT NULL
);

CREATE TABLE DIARISTA(
  ID_DIARISTA SERIAL UNIQUE PRIMARY KEY,
  NOME_DIARISTA VARCHAR(200) NOT NULL,
  ENDEREÇO VARCHAR(200) NOT NULL ,
  TELEFONE VARCHAR(30) NOT NULL
);

CREATE TABLE SERVIÇOS(
  ID_SERVIÇO SERIAL UNIQUE PRIMARY KEY,
  NOME_SERVIÇO VARCHAR(100) NOT NULL,
  VALOR_SERVIÇO FLOAT NOT NULL

);

CREATE TABLE SOLICITAÇÃO(
  ID_SOLICITAÇÃO SERIAL UNIQUE PRIMARY KEY ,
  ID_CLIENTE INT REFERENCES CLIENTE(ID_CLIENTE),
  ID_FUNCIONARIO INT REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
  VALOR_SOLICITAÇÃO FLOAT NOT NULL
);

CREATE TABLE DIARISTA_SERVIÇO(
  ID_DIARISTA INT REFERENCES DIARISTA(ID_DIARISTA),
  ID_SERVIÇO INT REFERENCES SERVIÇOS(ID_SERVIÇO)
);

CREATE TABLE SOLICITAÇÃO_SERVIÇO(
  ID_SOLICITAÇÃO INT REFERENCES SOLICITAÇÃO(ID_SOLICITAÇÃO),
  ID_CLIENTE INT REFERENCES CLIENTE(ID_CLIENTE),
  ID_CATEGORIA_CLIENTE INT REFERENCES CATEGORIA_CLIENTE(ID_CATEGORIA),
  ID_FUNCIONARIO INT REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
  ID_SERVIÇO INT REFERENCES SERVIÇOS(ID_SERVIÇO),
  ID_DIARISTA INT REFERENCES DIARISTA(ID_DIARISTA)
);

